CREATE DATABASE QLSV
GO

USE QLSV

CREATE TABLE SinhVien(
masv CHAR(13) NOT NULL,
hoten NVARCHAR (30) NULL,
NGAYSINH VARCHAR(10) NULL,
CONSTRAINT pk_SinhVien PRIMARY KEY(masv),
)


CREATE TABLE Lop(
maLop CHAR(6) NOT NULL,
tenlop NVARCHAR(100) NULL,
CONSTRAINT pk_Lop PRIMARY KEY(maLop),
)


CREATE TABLE GVCN(
maLop CHAR(6) NOT NULL,
magv CHAR(6) NOT NULL,
HK VARCHAR(1) NOT NULL,
CONSTRAINT pk_GVCN PRIMARY KEY(maLop,magv),
CONSTRAINT fk_Lop_GVCN FOREIGN KEY(maLop) REFERENCES Lop(maLop),
CONSTRAINT fk_GiaoVien_GVCN FOREIGN KEY (magv) REFERENCES GiaoVien(magv),
)


CREATE TABLE LopSV(
maLop CHAR(6) NOT NULL,
maSV CHAR(6) NOT NULL,
ChucVu VARCHAR(50) NULL,
CONSTRAINT pk_LopSV PRIMARY KEY (maLop,maSV),
CONSTRAINT fk_Lop_LopSV FOREIGN KEY (maLop) REFERENCES Lop(maLop),
CONSTRAINT fk_SinhVien_LopSV FOREIGN KEY (maSV) REFERENCES SinhVien(masv),
)


CREATE TABLE GiaoVien (
magv CHAR(6) NOT NULL,
hoten NVARCHAR(30) NOT NULL,
NgaySinh DATE NULL,
maBM NCHAR(6) NULL,
CONSTRAINT pk_GiaoVien PRIMARY KEY (magv),
CONSTRAINT fk_BoMon_GiaoVien FOREIGN KEY (maBM) REFERENCES BoMon(MaBM),
);


CREATE TABLE BoMon (
MaBM NCHAR(6) NOT NULL,
tenBM NVARCHAR(100) NULL,
maKhoa NCHAR(7) NULL,
CONSTRAINT pk_BoMon PRIMARY KEY (MaBM),
CONSTRAINT fk_Khoa_BoMon FOREIGN KEY (maKhoa) REFERENCES Khoa(maKhoa),
);


CREATE TABLE Khoa (
    maKhoa NCHAR(7) NOT NULL,
    tenKhoa NVARCHAR(100)
CONSTRAINT pk_Khoa PRIMARY KEY (maKhoa),
);


CREATE TABLE MonHoc (
    mamon NCHAR(6) NOT NULL,
    Tenmon NVARCHAR(100),
    STC CHAR(3) NOT NULL,
);


CREATE TABLE LopHP (
maLopHP CHAR(6) NOT NULL,
TenLopHP NVARCHAR(100) NULL,
HK VARCHAR(10) NULL,
maMon VARCHAR(6) NULL,
maGV CHAR(6) NULL,
CONSTRAINT pk_LopHP PRIMARY KEY (maLopHP),
CONSTRAINT fk_MonHoc_LopHP FOREIGN KEY (maMon) REFERENCES MonHoc(mamon),
CONSTRAINT fk_GiaoVien_LopHP FOREIGN KEY (maGV) REFERENCES GiaoVien(magv),
);


CREATE TABLE DKMH (
maLopHP CHAR(6) NOT NULL,
maSV CHAR(13) NOT NULL,
DiemTP INT NULL,
DiemThi INT NULL,
PhanTramThi NCHAR(10) NOT NULL,
CONSTRAINT pk_DKMH PRIMARY KEY (maLopHP,maSV),
CONSTRAINT fk_LopHP_DKMH FOREIGN KEY (maLopHP) REFERENCES LopHP(maLopHP),
CONSTRAINT fk_SinhVien_DKMH FOREIGN KEY (maSV) REFERENCES SinhVien(masv),
);